host: 0.0.0.0
port: 9091

session:
  name: authelia_session
  expiration: 3600
  inactivity: 300
  domain: example.com

storage:
  local:
    path: /config/db.sqlite3

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

notifier:
  disable_startup_check: false

  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: deny

  rules:
    - domain: example.com
      policy: one_factor
    - domain: traefik.example.com
      policy: one_factor
    - domain: portainer.example.com
      policy: one_factor
    - domain: alertmanager.example.com
      policy: one_factor
    - domain: prometheus.example.com
      policy: one_factor
    - domain: grafana.example.com
      policy: one_factor
    - domain: kibana.example.com
      policy: one_factor

authentication_backend:
  file:
    path: /config/users_database.yml
