version: "3.7"

networks:
  default:
    attachable: true
    name: "ioth_overlay_trafeik"

services:
  traefik:
    image: "traefik:${TRAEFIK_VERSION}"
    environment:
      - "TZ"
      - "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL"
    ports:
      - target: 80
        published: 80
        protocol: "tcp"
        mode: "host"
      - target: 443
        published: 443
        protocol: "tcp"
        mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./data/traefik/acme.json:/acme.json"
      - "./data/traefik/config:/config"
      - "./data/traefik/logs:/logs"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
        - "traefik.http.routers.traefik.entrypoints=web-secure"
        - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik.middlewares=authelia@docker"
        - "traefik.http.routers.traefik.service=api@internal"
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"

  authelia:
    image: "authelia/authelia:${AUTHELIA_VERSION}"
    volumes:
      - "./data/authelia:/config"
    environment:
      - "TZ"
      - "AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt"
      - "AUTHELIA_SESSION_SECRET_FILE=/config/secrets/session"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      resources:
        limits:
          memory: "2048M"
        reservations:
          memory: "1024M"
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.authelia-frontend.loadbalancer.server.port=9091"
        - "traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN_NAME}`)"
        - "traefik.http.routers.authelia.entrypoints=web-secure"
        - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN_NAME}/"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups"
