version: '3.7'

networks:
  default:
    driver: "overlay"
    name: "ioth_overlay_portainer"
    attachable: true
  traefik:
    external: true
    name: "ioth_overlay_trafeik"

services:
  agent:
    image: "portainer/agent"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    deploy:
      mode: "global"
      placement:
        constraints:
          - "node.platform.os == linux"
      resources:
        limits:
          memory: "128M"
        reservations:
          memory: "64M"

  portainer:
    image: "portainer/portainer:${PORTAINER_VERSION}"
    command: "-H tcp://tasks.agent:9001 --tlsskipverify --no-auth --no-analytics"
    volumes:
      - "./data/portainer:/data"
    networks:
      - "default"
      - "traefik"
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      resources:
        limits:
          memory: "128M"
        reservations:
          memory: "64M"
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.portainer-frontend.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
        - "traefik.http.routers.portainer.entrypoints=web-secure"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
        - "traefik.http.routers.portainer.middlewares=authelia@docker"
