version: "3.7"

networks:
  default:
    external: true
    name: "ioth_overlay_logs"

services:
  fluentd:
    build:
      context: "./fluentd"
      dockerfile: "./Dockerfile"
      args:
        FLUENTD_VERSION: "${FLUENTD_VERSION}"
    restart: "always"
    ports:
      - "${INTERNAL_BIND_IP-0.0.0.0}:24224:24224"
      - "${INTERNAL_BIND_IP-0.0.0.0}:24224:24224/udp"
    environment:
      - "TZ"
      - "FLUENTD_CONF=fluent.conf"
    volumes:
      - "./data/fluent/fluent.conf:/fluentd/etc/fluent.conf"

# source: https://github.com/bekkerstacks/elasticsearch-fluentd-kibana
