/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerSpec
 */
export interface ContainerSpec {
    /**
     * 
     * @type {string}
     * @memberof ContainerSpec
     */
    image?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContainerSpec
     */
    cmd?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContainerSpec
     */
    args?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ContainerSpec
     */
    hostname?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContainerSpec
     */
    env?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ContainerSpec
     */
    dir?: string;
}

export function ContainerSpecFromJSON(json: any): ContainerSpec {
    return ContainerSpecFromJSONTyped(json, false);
}

export function ContainerSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': !exists(json, 'image') ? undefined : json['image'],
        'cmd': !exists(json, 'cmd') ? undefined : json['cmd'],
        'args': !exists(json, 'args') ? undefined : json['args'],
        'hostname': !exists(json, 'hostname') ? undefined : json['hostname'],
        'env': !exists(json, 'env') ? undefined : json['env'],
        'dir': !exists(json, 'dir') ? undefined : json['dir'],
    };
}

export function ContainerSpecToJSON(value?: ContainerSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'cmd': value.cmd,
        'args': value.args,
        'hostname': value.hostname,
        'env': value.env,
        'dir': value.dir,
    };
}


