/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeJoin
 */
export interface NodeJoin {
    /**
     * 
     * @type {string}
     * @memberof NodeJoin
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeJoin
     */
    addr?: string;
}

export function NodeJoinFromJSON(json: any): NodeJoin {
    return NodeJoinFromJSONTyped(json, false);
}

export function NodeJoinFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeJoin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'addr': !exists(json, 'addr') ? undefined : json['addr'],
    };
}

export function NodeJoinToJSON(value?: NodeJoin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'addr': value.addr,
    };
}


