/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Platform
 */
export interface Platform {
    /**
     * 
     * @type {string}
     * @memberof Platform
     */
    architecture?: string;
    /**
     * 
     * @type {string}
     * @memberof Platform
     */
    os?: string;
}

export function PlatformFromJSON(json: any): Platform {
    return PlatformFromJSONTyped(json, false);
}

export function PlatformFromJSONTyped(json: any, ignoreDiscriminator: boolean): Platform {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'architecture': !exists(json, 'architecture') ? undefined : json['architecture'],
        'os': !exists(json, 'os') ? undefined : json['os'],
    };
}

export function PlatformToJSON(value?: Platform | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'architecture': value.architecture,
        'os': value.os,
    };
}


