/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProxyId
 */
export interface ProxyId {
    /**
     * 
     * @type {string}
     * @memberof ProxyId
     */
    id?: string;
}

export function ProxyIdFromJSON(json: any): ProxyId {
    return ProxyIdFromJSONTyped(json, false);
}

export function ProxyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxyId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ProxyIdToJSON(value?: ProxyId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


