/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Resources
 */
export interface Resources {
    /**
     * 
     * @type {number}
     * @memberof Resources
     */
    nanoCpus?: number;
    /**
     * 
     * @type {number}
     * @memberof Resources
     */
    memoryBytes?: number;
}

export function ResourcesFromJSON(json: any): Resources {
    return ResourcesFromJSONTyped(json, false);
}

export function ResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resources {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nanoCpus': !exists(json, 'nano_cpus') ? undefined : json['nano_cpus'],
        'memoryBytes': !exists(json, 'memory_bytes') ? undefined : json['memory_bytes'],
    };
}

export function ResourcesToJSON(value?: Resources | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nano_cpus': value.nanoCpus,
        'memory_bytes': value.memoryBytes,
    };
}


