/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceId
 */
export interface ServiceId {
    /**
     * 
     * @type {string}
     * @memberof ServiceId
     */
    id?: string;
}

export function ServiceIdFromJSON(json: any): ServiceId {
    return ServiceIdFromJSONTyped(json, false);
}

export function ServiceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ServiceIdToJSON(value?: ServiceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


