/* tslint:disable */
/* eslint-disable */
/**
 * IoT Honeypot API
 * IoT Honeypot API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xsedivy@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceStatus
 */
export interface ServiceStatus {
    /**
     * 
     * @type {number}
     * @memberof ServiceStatus
     */
    running?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceStatus
     */
    desired?: number;
}

export function ServiceStatusFromJSON(json: any): ServiceStatus {
    return ServiceStatusFromJSONTyped(json, false);
}

export function ServiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'running': !exists(json, 'running') ? undefined : json['running'],
        'desired': !exists(json, 'desired') ? undefined : json['desired'],
    };
}

export function ServiceStatusToJSON(value?: ServiceStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'running': value.running,
        'desired': value.desired,
    };
}


