#!/bin/sh
cd "$(dirname "$0")"

docker run --rm -it \
    --name "ioth_server" \
    -v "${PWD}/../:/app" \
    -e 'DOCKER_API_VERSION=1.39' \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    --entrypoint "/bin/bash" \
    ioth_server_img;
